FORMAT: 1A
HOST: http://www.google.com

# UH CMS API v1
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Components
Components related resources of the **Components API**

## Components Collection [/components]
### List all Components [GET]
+ Response 200 (application/json)

    + Header
    
            Connection: close
            Content-Length: 551
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Headers: Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Api-Version, Response-Time
            Access-Control-Allow-Methods: GET
            Access-Control-Expose-Headers: Api-Version, Request-Id, Response-Time
            Content-MD5: P8qSOAGOmSWp6TvLSMAC5g==
            Date: Fri, 24 Jan 2014 22:56:51 GMT
            Server: uh-express-api
            Request-Id: d0364ae0-854a-11e3-8524-bd243e344eb9
            Response-Time: 4
    
    + Body

            {
                "elapsed_time": 2,
                "entries": [
                    {
                        "component_id": 1,
                        "modified_by": 1,
                        "name": "Universal Header",
                        "timestamp": "2010-08-19T21:39:47.000Z"
                    },
                    {
                        "component_id": 5,
                        "modified_by": 0,
                        "name": "src_code",
                        "timestamp": "2010-09-01T00:49:07.000Z"
                    },
                    {
                        "component_id": 6,
                        "modified_by": 0,
                        "name": "signed_in_as",
                        "timestamp": "2010-09-01T01:03:37.000Z"
                    },
                    {
                        "component_id": 7,
                        "modified_by": 0,
                        "name": "network_link",
                        "timestamp": "2010-09-01T05:52:16.000Z"
                    },
                    {
                        "component_id": 8,
                        "modified_by": 0,
                        "name": "fr_code",
                        "timestamp": "2010-09-01T07:01:05.000Z"
                    }
                ],
                "inputs": {
                    "count": 5,
                    "start": 0
                },
                "success": true
            }
            

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
