FORMAT: 1A
HOST: http://www.google.com

# UH CMS API v1
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Components
Components related resources of the **Components API**

## Components Collection [/components]
### List all Components [GET]
+ Response 200 (application/json)

    + Header
    
        HTTP/1.1 200 OK
        Connection: close
        Content-Type: application/json
        Content-Length: 551
        Access-Control-Allow-Origin: *
        Access-Control-Allow-Headers: Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Api-Version, Response-Time
        Access-Control-Allow-Methods: GET
        Access-Control-Expose-Headers: Api-Version, Request-Id, Response-Time
        Content-MD5: P8qSOAGOmSWp6TvLSMAC5g==
        Date: Fri, 24 Jan 2014 22:56:51 GMT
        Server: uh-express-api
        Request-Id: d0364ae0-854a-11e3-8524-bd243e344eb9
        Response-Time: 4
    

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
